# Generated by Django 5.1.3 on 2025-01-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='last_modified_date',
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(choices=[('sick_leave', 'Sick Leave'), ('annual_leave', 'Annual Leave'), ('unpaid_leave', 'Unpaid Leave')], max_length=40),
        ),
    ]
