# Generated by Django 5.1.3 on 2025-01-03 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcondition',
            name='treatment',
        ),
        migrations.AddField(
            model_name='patienttreatment',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dental_plan.treatment'),
        ),
        migrations.AlterField(
            model_name='patientcondition',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dental_plan.condition'),
        ),
        migrations.AlterField(
            model_name='patientcondition',
            name='d3_image',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienttreatment',
            name='d3_image',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
