# Generated by Django 5.1.3 on 2025-01-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_plan', '0002_remove_patientcondition_treatment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcondition',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienttreatment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
