# Generated by Django 5.1.3 on 2025-01-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_plan', '0007_remove_patienttreatment_material_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttreatment',
            name='is_completed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
