# Generated by Django 5.1.3 on 2025-01-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_plan', '0009_remove_patienttreatment_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companytreamentproceduresession',
            name='session_duration',
        ),
        migrations.AddField(
            model_name='companytreamentproceduresession',
            name='session_duration_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companytreamentproceduresession',
            name='session_duration_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
