# Generated by Django 5.1.3 on 2025-01-19 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_plan', '0010_remove_companytreamentproceduresession_session_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentmaterialused',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='treatmentmaterialused',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='treatmentmaterialused',
            name='discounted_amount',
        ),
        migrations.RemoveField(
            model_name='treatmentmaterialused',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='treatmentmaterialused',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='treatmentmaterialused',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='treatmentmaterialused',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='treatmentmaterialused',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='treatmentmaterialused',
            name='patient_treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental_plan.companytreatmentprocedures'),
        ),
    ]
