# Generated by Django 5.1.3 on 2025-01-19 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_plan', '0012_alter_treatmentmaterialused_patient_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytreamentproceduresession',
            name='company_treatment_procedures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_treatment_procedure_sessions', to='dental_plan.companytreatmentprocedures'),
        ),
    ]
