# Generated by Django 5.1.3 on 2025-01-19 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_plan', '0013_alter_companytreamentproceduresession_company_treatment_procedures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentmaterialused',
            name='patient_treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_material_used', to='dental_plan.companytreatmentprocedures'),
        ),
    ]
