# Generated by Django 5.1.3 on 2025-01-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_clinicprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
