# Generated by Django 5.1.3 on 2025-01-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_client_created_by_client_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('Doctor', 'Doctor'), ('Intern', 'Intern'), ('Helper', 'Helper'), ('Client', 'Client'), ('User', 'User')], max_length=30, null=True, verbose_name='Profile Type'),
        ),
    ]
