# Generated by Django 5.1.3 on 2025-02-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_customuser_is_verified_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(default='signup', max_length=20),
        ),
    ]
