# Generated by Django 5.1.3 on 2025-01-16 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_structure', '0002_dentaldiagnosis_dentaltreatments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentaldiagnosisprocedures',
            name='dental_service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dental_structure.dentaldiagnosistypes'),
        ),
        migrations.AlterField(
            model_name='dentaldiagnosistypes',
            name='service_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dental_structure.dentaldiagnosis'),
        ),
    ]
