# Generated by Django 5.1.3 on 2025-01-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_structure', '0003_alter_dentaldiagnosisprocedures_dental_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalstructure',
            name='dental_numbering',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
